In [4]:
import glob, os
import pandas as pd
import nibabel as nib
import numpy as np

In [14]:
classes = {1 : 'eye',
          2 : 'nerve',
          3: 'tumor',
          4: 'ret_det'}

# Masks and classes

In [5]:
masks = glob.glob('/home/orco/data/Orbita_AI/Dataset/labels/*/*.nii.gz')
len(masks)

30

In [21]:
sids = [i.split('/')[-2] for i in masks]
sids[0]

'12120492'

In [10]:
masksm = '/home/orco/data/Orbita_AI/Dataset/labels/{sid}/{sid}.nii.gz'

In [17]:
l = []
for i in sids:
    mask = masksm.format(sid=i)
    nii = nib.load(mask)
    nii_arr = nii.get_fdata().astype(np.uint8)
    tissues = np.unique(nii_arr)
    has_tissues = [i in np.unique(nii_arr) for i in classes.keys()]
    l.append([i] + has_tissues)

In [19]:
df = pd.DataFrame(l)
df.columns = ['sid'] + ['has_{}'.format(classes[i]) for i in classes.keys()]

In [20]:
df.head()

sid  has_eye  has_nerve  has_tumor  has_ret_det
0  12120492     True       True      False        False
1  11908918     True       True      False        False
2  12273112     True       True      False        False
3  12244752     True       True       True         True
4  11931037     True       True       True         True

In [38]:
df.describe()

sid has_eye has_nerve has_tumor has_ret_det
count         30      30        30        30          30
unique        29       1         1         2           2
top     11883011    True      True      True        True
freq           2      30        30        17          22

In [39]:
# Check Keys

In [40]:
for i in glob.glob('/home/meddebma/Projects/Orbita_AI/nnUNet/nnUNet_raw/Dataset001_test/labelsTr/*.nii.gz'):
    print(np.unique(nib.load(i).get_fdata().astype(np.uint8)))

[0 1 2]
[0 1 2 4]
[0 1 2]
[0 1 2]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2]
[0 1 2]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2]
[0 1 2]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2 4]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2]
[0 1 2 3 4]
[0 1 2 4]
[0 1 2 3 4]
